In [1]:
from numpy import *

In [2]:
# define the number of movies in our 'database'

num_movies = 10

In [3]:
# define the number of users in our 'database'

num_users = 5

In [4]:
# randomly initialize some movie ratings 
# a 10 X 5 matrix

ratings = random.randint(11, size = (num_movies, num_users))

In [6]:
print (ratings)

[[ 6  5  7  3  6]
 [ 1  0  9  7  7]
 [ 2 10  4  5  1]
 [ 8  8  4  0  3]
 [ 7  0 10  0  9]
 [10  0  4  3  1]
 [ 3  3 10  3  1]
 [ 8  1  1  5  4]
 [ 7 10  2  6  1]
 [ 8  4  8 10  6]]


In [7]:
# create a logical matrix (matrix that represents whether a rating was made, or not)
# != is the logical not operator

did_rate = (ratings != 0) * 1

In [8]:
print (did_rate)

[[1 1 1 1 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 0 1]
 [1 0 1 0 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
print (ratings != 0)

[[ True  True  True  True  True]
 [ True False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True False  True]
 [ True False  True False  True]
 [ True False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [11]:
print ((ratings != 0) * 1)

[[1 1 1 1 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 0 1]
 [1 0 1 0 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
# Get the dimensions of a matrix using the shape property

ratings.shape

(10, 5)

In [13]:
did_rate.shape

(10, 5)

In [14]:
divyesh_ratings = zeros((num_movies, 1))
print (divyesh_ratings)


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [15]:
# I rate 3 movies

divyesh_ratings[0] = 8
divyesh_ratings[4] = 7
divyesh_ratings[7] = 3

print (divyesh_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [17]:
# Update ratings and did_rate

ratings = append(divyesh_ratings, ratings, axis = 1)
did_rate = append(((divyesh_ratings != 0) * 1), did_rate, axis = 1)


In [19]:
print (ratings)

[[ 8.  6.  5.  7.  3.  6.]
 [ 0.  1.  0.  9.  7.  7.]
 [ 0.  2. 10.  4.  5.  1.]
 [ 0.  8.  8.  4.  0.  3.]
 [ 7.  7.  0. 10.  0.  9.]
 [ 0. 10.  0.  4.  3.  1.]
 [ 0.  3.  3. 10.  3.  1.]
 [ 3.  8.  1.  1.  5.  4.]
 [ 0.  7. 10.  2.  6.  1.]
 [ 0.  8.  4.  8. 10.  6.]]


In [20]:
ratings.shape

(10, 6)

In [21]:
did_rate

array([[1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1]])

In [22]:
print(did_rate)

[[1 1 1 1 1 1]
 [0 1 0 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 0 1]
 [1 1 0 1 0 1]
 [0 1 0 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]]


In [23]:
did_rate.shape

(10, 6)

In [24]:
# a function that normalizes a dataset

def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = where(did_rate[i] == 1)[0]
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean


In [25]:
# Normalize ratings

ratings, ratings_mean = normalize_ratings(ratings, did_rate)

In [26]:
# Update some key variables now

num_users = ratings.shape[1]
num_features = 3



In [27]:
# Initialize Parameters theta (user_prefs), X (movie_features)

movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

In [29]:
print (movie_features)

[[ 0.3802754  -1.02999917  0.67240241]
 [-0.14803089 -1.63363073 -1.62542286]
 [-1.49913931 -0.87020857 -0.47370453]
 [ 0.35396483  0.00671762  1.10381178]
 [ 1.13822591 -0.82488456  0.4890082 ]
 [ 1.81577539 -0.34169715 -0.4586732 ]
 [-1.55638772 -0.9813944  -0.52989511]
 [-1.09852356  2.920731   -1.64005467]
 [ 0.33766961  0.99527431 -0.10068858]
 [ 1.48034997  0.69431147 -0.48194877]]


In [30]:
print (user_prefs)

[[ 0.58717502  0.69977156  0.34236276]
 [-0.45241085 -0.21589336  0.31998823]
 [-1.31300638  1.08258085 -0.51013089]
 [-1.14399504  0.28245536 -0.36850902]
 [ 0.21085069  1.67728676  0.35304294]
 [ 1.19056849  0.45704226  0.70908389]]


In [31]:
print (initial_X_and_theta)

[ 0.3802754  -0.14803089 -1.49913931  0.35396483  1.13822591  1.81577539
 -1.55638772 -1.09852356  0.33766961  1.48034997 -1.02999917 -1.63363073
 -0.87020857  0.00671762 -0.82488456 -0.34169715 -0.9813944   2.920731
  0.99527431  0.69431147  0.67240241 -1.62542286 -0.47370453  1.10381178
  0.4890082  -0.4586732  -0.52989511 -1.64005467 -0.10068858 -0.48194877
  0.58717502 -0.45241085 -1.31300638 -1.14399504  0.21085069  1.19056849
  0.69977156 -0.21589336  1.08258085  0.28245536  1.67728676  0.45704226
  0.34236276  0.31998823 -0.51013089 -0.36850902  0.35304294  0.70908389]


In [32]:
initial_X_and_theta.shape

(48,)

In [33]:
movie_features.T.flatten().shape

(30,)

In [34]:
user_prefs.T.flatten().shape

(18,)

In [35]:
initial_X_and_theta

array([ 0.3802754 , -0.14803089, -1.49913931,  0.35396483,  1.13822591,
        1.81577539, -1.55638772, -1.09852356,  0.33766961,  1.48034997,
       -1.02999917, -1.63363073, -0.87020857,  0.00671762, -0.82488456,
       -0.34169715, -0.9813944 ,  2.920731  ,  0.99527431,  0.69431147,
        0.67240241, -1.62542286, -0.47370453,  1.10381178,  0.4890082 ,
       -0.4586732 , -0.52989511, -1.64005467, -0.10068858, -0.48194877,
        0.58717502, -0.45241085, -1.31300638, -1.14399504,  0.21085069,
        1.19056849,  0.69977156, -0.21589336,  1.08258085,  0.28245536,
        1.67728676,  0.45704226,  0.34236276,  0.31998823, -0.51013089,
       -0.36850902,  0.35304294,  0.70908389])

In [37]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
    # Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
    # --------------------------------------------------------------------------------------------------------------
    # Get the first 30 (10 * 3) rows in the 48 X 1 column vector
    first_30 = X_and_theta[:num_movies * num_features]
    # Reshape this column vector into a 10 X 3 matrix
    X = first_30.reshape((num_features, num_movies)).transpose()
    # Get the rest of the 18 the numbers, after the first 30
    last_18 = X_and_theta[num_movies * num_features:]
    # Reshape this column vector into a 6 X 3 matrix
    theta = last_18.reshape(num_features, num_users ).transpose()
    return X, theta

In [39]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
    
    # we multiply by did_rate because we only want to consider observations for which a rating was given
    difference = X.dot( theta.T ) * did_rate - ratings
    X_grad = difference.dot( theta ) + reg_param * X
    theta_grad = difference.T.dot( X ) + reg_param * theta
    
    # wrap the gradients back into a column vector 
    return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [40]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
    
    # we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
    cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
    # '**' means an element-wise power
    regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
    return cost + regularization

In [41]:
# import these for advanced optimizations (like gradient descent)

from scipy import optimize

In [45]:
# regularization paramater

reg_param = 30
minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta, args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), maxiter=100, disp=True, full_output=True ) 

Optimization terminated successfully.
         Current function value: 165.733333
         Iterations: 11
         Function evaluations: 23
         Gradient evaluations: 23


In [46]:
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]


In [47]:
movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)

In [49]:
print (movie_features)

[[-1.24014113e-07 -7.59897362e-08 -1.01693192e-08]
 [-5.94134908e-08 -2.66293956e-08 -3.36224132e-08]
 [-4.07690467e-08  4.23436534e-09 -2.60774637e-08]
 [ 7.67187457e-09  1.76164408e-08  7.50915850e-10]
 [ 1.54754142e-07  8.08967082e-08  5.46473507e-08]
 [ 8.85091647e-08  5.44001926e-08  4.04168147e-08]
 [ 4.65661368e-08  1.07880832e-07  3.94524827e-08]
 [ 1.57029230e-08  1.12534995e-08 -5.74709402e-09]
 [-1.66326582e-08  2.76379415e-08 -2.62654946e-08]
 [-1.05870229e-07  3.80454607e-09 -6.43753980e-08]]


In [50]:
print (user_prefs)

[[ 4.43575029e-08 -4.93998864e-08  1.08739383e-07]
 [ 1.74147621e-08  9.45178398e-08  1.48058788e-08]
 [-1.07312425e-07 -1.50635091e-07  1.55848602e-08]
 [ 1.65640379e-08  2.04379413e-07  3.40137238e-08]
 [ 1.46923237e-09  7.00086927e-08 -1.41666735e-07]
 [-8.30788746e-09 -1.04770645e-07 -5.79846589e-09]]


In [51]:

# Make some predictions (movie recommendations). Dot product

all_predictions = movie_features.dot( user_prefs.T )

In [53]:
print(all_predictions)

[[-2.85287753e-15 -9.49262769e-15  2.45964885e-14 -1.79308086e-14
  -4.06149339e-15  9.05075540e-15]
 [-4.97602544e-15 -4.04943413e-15  9.86312656e-15 -7.57025104e-15
   2.81159611e-15  3.47853796e-15]
 [-4.85323759e-15 -6.95859951e-16  3.33076761e-15 -6.96874578e-16
   3.93085232e-15  4.62767480e-17]
 [-4.48290849e-16  1.80978977e-15 -3.46523870e-15  3.75305649e-15
   1.13819596e-15 -1.91377709e-15]
 [ 8.81053830e-15  1.11502907e-14 -2.79412538e-14  2.09557351e-14
  -1.85086918e-15 -1.00781511e-14]
 [ 5.63358169e-15  7.28156120e-15 -1.70628206e-14  1.39590750e-14
  -1.78719128e-15 -6.66922296e-15]
 [ 1.02629532e-15  1.15917301e-14 -2.06329026e-14  2.41618703e-14
   2.03190810e-15 -1.19183745e-14]
 [-4.84314600e-16  1.25202835e-15 -3.46985832e-15  2.36460736e-15
   1.62508607e-15 -1.27617019e-15]
 [-4.95918804e-15  1.93374101e-15 -2.78769701e-15  4.47973501e-15
   5.63140578e-15 -2.60516313e-15]
 [-1.18842242e-14 -2.43724171e-15  9.78481123e-15 -3.16571460e-15
   9.23065577e-15  8.5423

In [57]:
# add back the ratings_mean column vector to my (our) predictions

predictions_for_divyesh = all_predictions[:, 0:1] + ratings_mean

In [58]:
print (predictions_for_divyesh)

[[5.83333333]
 [6.        ]
 [4.4       ]
 [5.75      ]
 [8.25      ]
 [4.5       ]
 [4.        ]
 [3.66666667]
 [5.2       ]
 [7.2       ]]


In [59]:
print (divyesh_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]
